FROM  maven:3.9.9-eclipse-temurin-11-alpine AS build
COPY . .
RUN mvn package -DskipTests


FROM eclipse-temurin-11-alpine
COPY --from=build target/DockerApp.jar app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]